# Generated by Django 5.0.6 on 2024-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delhi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='audio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='projector',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='screen_size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seats',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='surroundings',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='travel',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
