# Generated by Django 5.0.6 on 2024-06-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delhi', '0002_alter_cinema_audio_alter_cinema_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='screen_size',
            new_name='screen',
        ),
    ]
